public enum GAMEPLAY_STATUS {
    PREPARING = 0,
    IDLE,
    SERVING,
    ITEM_REQUESTED,
    ITEM_RETRIEVE,
    ITEM_WAIT_PLY_PICKUP,
    ITEM_SHIPPING,
    THINKING,
    WEIGHT_ITEM,
    WIN,
    GAMEOVER
}
